"use client"

import { useState } from "react"
import { ArrowDownIcon, ArrowUpIcon, CaretDownIcon, CaretRightIcon, PlusIcon, TrashIcon } from "@phosphor-icons/react"

import { Button } from "@/components/shadcn/button"
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/shadcn/dialog"

import type { BuilderEntityId, BuilderQuestion } from "../model/builder.types"
import { useBuilderActions, useBuilderDocument, useBuilderExpandedIds, useBuilderSelection, useBuilderValidation } from "../store/exam-builder.store"
import { QUESTION_TYPE_LABELS } from "./builder-labels"

export function ExamBuilderOutline({ readOnly, onSelect }: { readOnly: boolean; onSelect?: () => void }) {
	const document = useBuilderDocument(); const selection = useBuilderSelection(); const expanded = useBuilderExpandedIds(); const actions = useBuilderActions(); const validation = useBuilderValidation()
	const [deletion, setDeletion] = useState<{ kind: "section"|"question"; id: BuilderEntityId; title: string; cascade: string } | null>(null)
	if (!document) return null
	function select(next: Parameters<typeof actions.setSelection>[0]) { actions.setSelection(next); onSelect?.() }
	function addQuestion(sectionId: BuilderEntityId, type: BuilderQuestion["type"] = "single-choice", parentGroupId?: BuilderEntityId) { const id = actions.createQuestion(sectionId, type, parentGroupId); if (id) { actions.setExpanded(parentGroupId ?? sectionId, true); select({ type: "question", questionId: id }) } }
	return <nav aria-label="Exam outline" className="h-full overflow-y-auto p-3">
		<button type="button" onClick={() => select({ type: "version" })} className={`mb-3 w-full border p-3 text-left font-medium ${selection.type === "version" ? "border-primary bg-primary/5" : "hover:bg-muted"}`}>Version settings</button>
		<div className="mb-2 flex items-center justify-between"><h2 className="font-semibold">Outline</h2>{!readOnly && <Button size="icon-sm" variant="ghost" aria-label="Create section" onClick={() => { const id = actions.createSection(); if (id) select({ type: "section", sectionId: id }) }}><PlusIcon /></Button>}</div>
		{document.sectionIds.map((sectionId, sectionIndex) => { const section = document.sectionsById[sectionId]; if (!section) return null; const open = Boolean(expanded[sectionId]); const hasError = validation.publish.some((error) => error.entityId === sectionId || section.questionIds.some((id) => error.entityId === id)); return <div key={sectionId} className="mb-2 border">
			<div className="flex items-center gap-1 p-1"><Button size="icon-sm" variant="ghost" aria-label={`${open ? "Collapse" : "Expand"} ${section.title}`} aria-expanded={open} onClick={() => actions.setExpanded(sectionId, !open)}>{open ? <CaretDownIcon /> : <CaretRightIcon />}</Button><button type="button" className={`min-w-0 flex-1 truncate px-1 py-2 text-left ${selection.type === "section" && selection.sectionId === sectionId ? "font-semibold text-primary underline" : ""}`} onClick={() => select({ type: "section", sectionId })}>{section.title || "Untitled section"}{hasError ? <span className="ml-1 text-destructive" aria-label="Contains validation errors">!</span> : null}</button>{!readOnly && <><MoveButtons label={section.title} index={sectionIndex} count={document.sectionIds.length} onMove={(direction) => actions.moveSection(sectionId, direction)} /><Button size="icon-sm" variant="ghost" aria-label={`Delete ${section.title}`} onClick={() => setDeletion({ kind: "section", id: sectionId, title: section.title, cascade: "All questions in this section will also be deleted." })}><TrashIcon /></Button></>}</div>
			{open && <div className="border-t p-2 pl-5"><div className="mb-1 flex justify-end">{!readOnly && <QuestionAdd onAdd={(type) => addQuestion(sectionId, type)} />}</div>{section.questionIds.map((questionId, index) => { const question = document.questionsById[questionId]; if (!question) return null; return <QuestionRow key={questionId} question={question} index={index} count={section.questionIds.length} readOnly={readOnly} selected={selection.type === "question" && selection.questionId === questionId} expanded={expanded} hasError={validation.publish.some((error) => error.entityId === questionId || (question.type === "group" && question.childQuestionIds.some((id) => error.entityId === id)))} onSelect={() => select({ type: "question", questionId })} onExpand={(next) => actions.setExpanded(questionId, next)} onAddChild={(type) => addQuestion(sectionId, type, questionId)} onMove={(direction) => actions.moveQuestion(questionId, direction)} onDelete={() => setDeletion({ kind: "question", id: questionId, title: QUESTION_TYPE_LABELS[question.type], cascade: question.type === "group" ? "All child questions in this Group will also be deleted." : "This staged question will be removed." })} selectChild={(id) => select({ type: "question", questionId: id })} /> })}{section.questionIds.length === 0 && <p className="py-3 text-center text-xs text-muted-foreground">No questions in this section.</p>}</div>}
		</div>})}
		{document.sectionIds.length === 0 && <p className="border border-dashed p-6 text-center text-sm text-muted-foreground">Create a section to start building this version.</p>}
		<Dialog open={Boolean(deletion)} onOpenChange={(open) => { if (!open) setDeletion(null) }}><DialogContent><DialogHeader><DialogTitle>Delete {deletion?.title}?</DialogTitle><DialogDescription>{deletion?.cascade} This change remains staged until Save All.</DialogDescription></DialogHeader><DialogFooter><DialogClose render={<Button variant="outline" />}>Cancel</DialogClose><Button variant="destructive" onClick={() => { if (!deletion) return; if (deletion.kind === "section") actions.deleteSection(deletion.id); else actions.deleteQuestion(deletion.id); setDeletion(null) }}>Delete</Button></DialogFooter></DialogContent></Dialog>
	</nav>
}

function QuestionRow({ question, index, count, readOnly, selected, expanded, hasError, onSelect, onExpand, onAddChild, onMove, onDelete, selectChild }: { question: BuilderQuestion; index: number; count: number; readOnly: boolean; selected: boolean; expanded: Record<string, true>; hasError: boolean; onSelect: () => void; onExpand: (open: boolean) => void; onAddChild: (type: BuilderQuestion["type"]) => void; onMove: (direction: -1|1) => void; onDelete: () => void; selectChild: (id: BuilderEntityId) => void }) {
	const document = useBuilderDocument(); const actions = useBuilderActions(); const open = question.type === "group" && Boolean(expanded[question.id]); if (!document) return null
	return <div className="mb-1"><div className="flex items-center gap-1">{question.type === "group" ? <Button size="icon-sm" variant="ghost" aria-label={`${open ? "Collapse" : "Expand"} Group`} aria-expanded={open} onClick={() => onExpand(!open)}>{open ? <CaretDownIcon /> : <CaretRightIcon />}</Button> : <span className="w-7" />}<button type="button" onClick={onSelect} className={`min-w-0 flex-1 truncate py-2 text-left text-sm ${selected ? "font-semibold text-primary underline" : ""}`}>{QUESTION_TYPE_LABELS[question.type]}{hasError ? <span className="ml-1 text-destructive" aria-label="Has validation errors">!</span> : null}</button>{!readOnly && <><MoveButtons label={QUESTION_TYPE_LABELS[question.type]} index={index} count={count} onMove={onMove} /><Button size="icon-sm" variant="ghost" aria-label={`Delete ${QUESTION_TYPE_LABELS[question.type]}`} onClick={onDelete}><TrashIcon /></Button></>}</div>{open && question.type === "group" ? <div className="ml-7 border-l pl-2"><div className="flex justify-end">{!readOnly && <QuestionAdd child onAdd={onAddChild} />}</div>{question.childQuestionIds.map((id, childIndex) => <div key={id} className="flex items-center"><button type="button" onClick={() => selectChild(id)} className="min-w-0 flex-1 truncate px-2 py-2 text-left text-sm hover:bg-muted">{QUESTION_TYPE_LABELS[document.questionsById[id]?.type ?? "fill-blank"]}</button>{!readOnly && <><MoveButtons label={`child question ${childIndex + 1}`} index={childIndex} count={question.childQuestionIds.length} onMove={(direction) => actions.moveQuestion(id, direction)} /><Button size="icon-sm" variant="ghost" aria-label={`Delete child question ${childIndex + 1}`} onClick={() => actions.deleteQuestion(id)}><TrashIcon /></Button></>}</div>)}</div> : null}</div>
}

function QuestionAdd({ child, onAdd }: { child?: boolean; onAdd: (type: Exclude<BuilderQuestion["type"], "group"> | BuilderQuestion["type"]) => void }) { return <select aria-label={child ? "Create child question" : "Create question"} defaultValue="" className="h-8 border bg-background px-2 text-xs" onChange={(e) => { if (e.target.value) onAdd(e.target.value as BuilderQuestion["type"]); e.target.value = "" }}><option value="" disabled>+ {child ? "Child" : "Question"}</option>{(["single-choice", "multiple-choice", "fill-blank", ...(child ? [] : ["group"])] as BuilderQuestion["type"][]).map((type) => <option key={type} value={type}>{QUESTION_TYPE_LABELS[type]}</option>)}</select> }
function MoveButtons({ label, index, count, onMove }: { label: string; index: number; count: number; onMove: (direction: -1|1) => void }) { return <><Button size="icon-sm" variant="ghost" aria-label={`Move ${label} up`} disabled={index === 0} onClick={() => onMove(-1)}><ArrowUpIcon /></Button><Button size="icon-sm" variant="ghost" aria-label={`Move ${label} down`} disabled={index === count - 1} onClick={() => onMove(1)}><ArrowDownIcon /></Button></> }
