// <auto-generated />
using System;
using ExamForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExamForgeDbContext))]
    [Migration("20260715142710_AddQuestionManagement")]
    partial class AddQuestionManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("examforge")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamForge.Domain.ExamAttempts.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExamVersionId");

                    b.HasIndex("ExamId", "UserId");

                    b.HasIndex("UserId", "StartedAtUtc");

                    b.ToTable("exam_attempts", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamAttempts.ExamAttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ExamAttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("exam_attempt_answers", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamAttempts.ExamAttemptSelectedOption", b =>
                {
                    b.Property<Guid>("ExamAttemptAnswerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("ExamAttemptAnswerId", "QuestionOptionId");

                    b.HasIndex("QuestionOptionId");

                    b.ToTable("exam_attempt_selected_options", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamClassifications.ExamCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("IsArchived", "DisplayOrder");

                    b.HasIndex("IsArchived", "IsFeatured", "DisplayOrder");

                    b.ToTable("exam_categories", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamClassifications.ExamCategoryTag", b =>
                {
                    b.Property<Guid>("ExamCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamTagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExamCategoryId", "ExamTagId");

                    b.HasIndex("ExamTagId", "ExamCategoryId");

                    b.ToTable("exam_category_tags", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamClassifications.ExamTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "Slug")
                        .IsUnique();

                    b.ToTable("exam_tags", "examforge");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2c9706e-d53d-4361-81f7-681bba2aea53"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tag use for testing",
                            IsArchived = false,
                            Name = "Test tag",
                            Slug = "test",
                            Type = "ExamType"
                        });
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("NextVersionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Type", "IsArchived");

                    b.HasIndex("IsArchived", "CreatedAtUtc", "Id");

                    b.ToTable("exams", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.ExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("StimulusText")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamVersionId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("ExamVersionId", "Kind", "DisplayOrder");

                    b.ToTable("exam_sections", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.ExamTagMapping", b =>
                {
                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamTagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExamId", "ExamTagId");

                    b.HasIndex("ExamTagId", "ExamId");

                    b.ToTable("exam_tag_mappings", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.ExamVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExamId")
                        .IsUnique()
                        .HasDatabaseName("ux_exam_versions_one_published_per_exam")
                        .HasFilter("\"Status\" = 'Published'");

                    b.HasIndex("ExamId", "Status");

                    b.HasIndex("ExamId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("Status", "PublishedAtUtc");

                    b.HasIndex("ExamId", "CreatedAtUtc", "Id");

                    b.ToTable("exam_versions", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.FillAnswerKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptedAnswer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("BlankKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedAnswer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "DisplayOrder");

                    b.HasIndex("QuestionId", "BlankKey", "NormalizedAnswer")
                        .IsUnique();

                    b.ToTable("fill_answer_keys", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExamSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParentQuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamSectionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_questions_top_level_order")
                        .HasFilter("\"ParentQuestionId\" IS NULL");

                    b.HasIndex("ExamSectionId", "Type");

                    b.HasIndex("ParentQuestionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_questions_child_order")
                        .HasFilter("\"ParentQuestionId\" IS NOT NULL");

                    b.ToTable("questions", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("QuestionId", "IsCorrect");

                    b.ToTable("question_options", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", "examforge");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamAttempts.ExamAttempt", b =>
                {
                    b.HasOne("ExamForge.Domain.Exams.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamForge.Domain.Exams.ExamVersion", "ExamVersion")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamForge.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ExamVersion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamAttempts.ExamAttemptAnswer", b =>
                {
                    b.HasOne("ExamForge.Domain.ExamAttempts.ExamAttempt", "ExamAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamForge.Domain.Exams.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamAttempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamAttempts.ExamAttemptSelectedOption", b =>
                {
                    b.HasOne("ExamForge.Domain.ExamAttempts.ExamAttemptAnswer", "ExamAttemptAnswer")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("ExamAttemptAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamForge.Domain.Exams.QuestionOption", "QuestionOption")
                        .WithMany()
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamAttemptAnswer");

                    b.Navigation("QuestionOption");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamClassifications.ExamCategoryTag", b =>
                {
                    b.HasOne("ExamForge.Domain.ExamClassifications.ExamCategory", "ExamCategory")
                        .WithMany("ExamCategoryTags")
                        .HasForeignKey("ExamCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamForge.Domain.ExamClassifications.ExamTag", "ExamTag")
                        .WithMany("ExamCategoryTags")
                        .HasForeignKey("ExamTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamCategory");

                    b.Navigation("ExamTag");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.ExamSection", b =>
                {
                    b.HasOne("ExamForge.Domain.Exams.ExamVersion", "ExamVersion")
                        .WithMany("Sections")
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamVersion");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.ExamTagMapping", b =>
                {
                    b.HasOne("ExamForge.Domain.Exams.Exam", "Exam")
                        .WithMany("ExamTagMappings")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamForge.Domain.ExamClassifications.ExamTag", "Tag")
                        .WithMany()
                        .HasForeignKey("ExamTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.ExamVersion", b =>
                {
                    b.HasOne("ExamForge.Domain.Users.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ExamForge.Domain.Exams.Exam", "Exam")
                        .WithMany("Versions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.FillAnswerKey", b =>
                {
                    b.HasOne("ExamForge.Domain.Exams.Question", "Question")
                        .WithMany("FillAnswerKeys")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.Question", b =>
                {
                    b.HasOne("ExamForge.Domain.Exams.ExamSection", "ExamSection")
                        .WithMany("Questions")
                        .HasForeignKey("ExamSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamForge.Domain.Exams.Question", "ParentQuestion")
                        .WithMany("ChildQuestions")
                        .HasForeignKey("ParentQuestionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ExamSection");

                    b.Navigation("ParentQuestion");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.QuestionOption", b =>
                {
                    b.HasOne("ExamForge.Domain.Exams.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ExamForge.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("ExamForge.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamAttempts.ExamAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamAttempts.ExamAttemptAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamClassifications.ExamCategory", b =>
                {
                    b.Navigation("ExamCategoryTags");
                });

            modelBuilder.Entity("ExamForge.Domain.ExamClassifications.ExamTag", b =>
                {
                    b.Navigation("ExamCategoryTags");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.Exam", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("ExamTagMappings");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.ExamSection", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.ExamVersion", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ExamForge.Domain.Exams.Question", b =>
                {
                    b.Navigation("ChildQuestions");

                    b.Navigation("FillAnswerKeys");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
